### ISSUE TITLE
Layering Combination Possibilities

### ISSUE THREAD

**Issue by mrtenda** [gjtorikian/Earthbound-Battle-Backgrounds-JS#1]
Hey there, first off let me say this is amazingly incredible!

Thought I would point out a minor possible inaccuracy: In your README.md, it says there are 52,650 combinations of backgrounds which potentially exist in EarthBound. As it turns out, the 327 background layers are divided into two groups:
- 250 background layers which use a 16-color palette
- 77 background layers which use a 4-color palette

EarthBound only ever displays backgrounds which are either composed of a single 16-color layer, or a combination of two 4-color layers. This is because combining a 16-color layer with anything else results in glitchiness, as the SNES's memory is not sufficiently large to handle it. So the EarthBound engine actually supports far fewer than 52,650 combinations. But your battle background renderer doesn't seem to have this same technical limitation, so I guess you could say your renderer is superior to the original one! :smile:

**Comment by gjtorikian** [comment]
Indeed! Do you think I should change this line:

> Obviously, this many don't exist in the game--they only potentially exist.

It would be absurd to claim there are 52,000 patterns in Earthbound, a game with far fewer enemies.  And, in fact, some patterns seem to repeat themselves. I don't know the rationale for why the memory addresses support up to 326 different layers, though.

**Comment by mrtenda** [comment]
Hm... The part I saw as inaccurate was this:

> 52,650 _possible_ different background combinations

There aren't that many which are possible in the EarthBound engine, due to the fact that the 16-color layers can only be displayed individually and cannot be combined. I'm a bit rusty on my combinatorics, but I think the amount of layer combinations which are possible in the EarthBound engine is (250 + C(77, 2)).

As a side note, to answer your question why there are 326 layers but there are <326 enemies in EarthBound: layer combinations in EarthBound are assigned to unique groupings of enemies, not each individual enemy. For example, when a Manly Fish and an Even Slimier Little Pile engage the party together in battle, layers 62 and 0 are used. But when a Manly Fish and a Hard Crocodile engage the party together in battle, layers 63 and 0 are used. There are 483 such "enemy groupings" in EarthBound, each which have an assigned layer combination.

**Comment by gjtorikian** [comment]
> layer combinations in EarthBound are assigned to unique groupings of enemies, not each individual enemy

Wow, that makes a lot of sense. 

Ughhh I kind of burned myself out working on this JS port. But I definitely believe this text should be fixed. I'll think about how to be more accurate over the next few days (unless you want to submit a Pull Request first :wink:).
