### ISSUE TITLE
Background data change issue

### ISSUE THREAD

**Issue by xianzhe18** [gjtorikian/Earthbound-Battle-Backgrounds-JS#10]
I am replicating this repo for the sake to change background.
The most interesting part is how you generated truncated_backgrounds.dat and where you use backgrounds.dat file.
I want to change the files with my own png files, but I cannot find proper documentary or method.

**Comment by gjtorikian** [comment]
To be clear, you want to generate a PNG file from the generated graphic? I am not sure what the question is!

**Comment by Kaleidosium** [comment]
@xianzhe18 https://github.com/IamRifki/EarthboundBackgrounds/releases/download/1.0.1/EarthboundBackground-x64.7z

**Comment by gjtorikian** [comment]
Cool!
