### ISSUE TITLE
I can't download/save anything

### ISSUE THREAD

**Issue by Starman99x** [gjtorikian/Earthbound-Battle-Backgrounds-JS#15]
This is a fantastic work but it's useless to me if I can't save generated backgrounds to my device (android phone).

**Comment by gjtorikian** [comment]
I'm sorry it's useless to you.

**Comment by Midcamper** [comment]
> I'm sorry it's useless to you.

You should add a method to save it as a gif since it would make wonders to many people

**Comment by Midcamper** [comment]
It may be a bit challenging but many would benefit from the work that you and others have put into this masterpiece
