### ISSUE TITLE
Mr. Batty (Suggested Layers)

### ISSUE THREAD

**Issue by tahutoa** [gjtorikian/Earthbound-Battle-Backgrounds-JS#16]
From all the images and footage I've found where Mr. Batty is the only enemy type to be found, the background used is 73,0. It _could_ be 72,0, admittedly but I don't think so: the footage I've seen has the BG moving too fast for it to be 72,0.

I have no idea who 89,0 is used for, but plain ol' Mr. Batty uses the same BG as Elder Batty and Arachnid!.

_(I would have put this under Pull Requests, if I had any idea how. It kept redirecting me and kept talking about comparisons for some reason, so I just gave up on that.)_

**Comment by gjtorikian** [comment]
I agree with your guess! I've added it in aaa928572743e076fcfd3996b6368a838c5fce27, thanks!
