### ISSUE TITLE
W and H are not being used in src/romlib/backgroundLayer.js

### ISSUE THREAD

**Issue by CapsAdmin** [gjtorikian/Earthbound-Battle-Backgrounds-JS#3]
(this is just a test issue, but a valid one i guess)

**Comment by VxJasonxV** [comment]
Yeah, they're being defined at https://github.com/gjtorikian/Earthbound-Battle-Backgrounds-JS/blob/gh-pages/src/romlib/backgroundLayer.js#L8-9, but never used.

I suspect that https://github.com/gjtorikian/Earthbound-Battle-Backgrounds-JS/blob/gh-pages/src/romlib/backgroundLayer.js#L111 is actually supposed to read:

``` javascript
    var pixels = new Int16Array(H * W * 4);
```

**Comment by gjtorikian** [comment]
Thanks!
